---
- name: Update dehydrated configuration
  lineinfile:
    path: "{{ config_filepath }}"
    regexp: "^{{ item.key|regex_escape }}="
    line: >
      {{ item.key|quote }}={{ item.value|quote }}
  loop_control:
    label: "{{ config_filepath }} {{ item.key }}={{ item.value }}"
  with_dict: "{{ dehydrated.config }}"
  vars:
    config_filepath: "{{ dehydrated.prefix.config }}/config"

- name: Template dehydrated hook
  template:
    src: hook.sh
    dest: "{{ item }}"
  with_items:
    - "{{ dehydrated.prefix.config }}/hook.sh"
