---
- name: Create dummy certificate directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "{{ cert_prefix }}"

- name: Copy dummy certificate and key
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    force: no
    mode: 0600
  loop_control:
    label: "{{ item.dest }}"
  with_items:
    - dest: "{{ cert_prefix }}/fullchain.pem"
      content: "{{ dehydrated.dummy_cert }}"
    - dest: "{{ cert_prefix }}/privkey.pem"
      content: "{{ dehydrated.dummy_key }}"
  notify:
    - Reload httpd service (and dehydrated certificates) before running dehydrated
    - Run dehydrated
    - Reload httpd service (and dehydrated certificates) after running dehydrated
